spring.application.name=accountService
server.port=8090

spring.datasource.url=jdbc:h2:file:./data/accountdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=account
spring.datasource.password=pass

# Make sure schema is generated
spring.jpa.hibernate.ddl-auto=update

# Optional: to see SQL
spring.jpa.show-sql=true

# Enable H2 console
spring.h2.console.enabled=true