spring.application.name=loggingService
server.port=8095

spring.datasource.url=jdbc:h2:file:./data/loggingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=logging
spring.datasource.password=

# Make sure schema is generated
spring.jpa.hibernate.ddl-auto=update

# Optional: to see SQL
spring.jpa.show-sql=true

# Enable H2 console
spring.h2.console.enabled=true

spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=logging-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
